import { KPI_MASTER, DEPTS, ABS_PARAMS } from './master-data.js';
import { MONTHS,getCurrentFiscalMonth,setStatus,getAllDocsFB,tableToExcel,tableToPpt,configOk } from './common.js';
const kpiTable=document.getElementById('kpiDashTable'), absTable=document.getElementById('absDashTable'), cards=document.getElementById('summaryCards');
function safeId(s){return s.replace(/[^a-zA-Z0-9]/g,'_')}
function mClass(m){return m===getCurrentFiscalMonth()?'month-current':'month-other'}
function tdClass(m){return m===getCurrentFiscalMonth()?' class="month-current-cell"':''}
function fmt(x){ if(x===''||x===undefined||x===null) return ''; const n=Number(x); return Number.isFinite(n)?(Math.round(n*100)/100):x; }
function calcDivision(asaved,m,p){ if(p.type==='text'){ return DEPTS.map(d=>(asaved[`${m}_${d}`]||{})[p.key]).filter(Boolean).join(' | '); } const vals=DEPTS.map(d=>Number((asaved[`${m}_${d}`]||{})[p.key])).filter(v=>Number.isFinite(v)); if(!vals.length) return ''; const sum=vals.reduce((a,b)=>a+b,0); return p.calc==='avg'?fmt(sum/vals.length):fmt(sum); }
async function load(){ if(!configOk){setStatus('Firebase config missing. Dashboard cannot show other PC data.','bad'); return;} setStatus('Loading all 12 months from Firebase...'); try{const ksaved=await getAllDocsFB('kpis'); const asaved=await getAllDocsFB('absot'); const cur=getCurrentFiscalMonth(); cards.innerHTML=`<div class="summary-card"><b>Current Month:</b> <span style="color:#003b7a;font-weight:bold">${cur}</span></div><div class="summary-card"><b>Abs & OT:</b> MF+ME+UM+UE+SE combined with Division Avg / Total</div><div class="summary-card"><b>Rule:</b> % and Hrs/Person = Avg, Leaves/OT Hrs/Count = Total</div>`;
let khtml='<tr><th>Area</th><th>Parameter</th><th>Target</th>'+MONTHS.map(m=>`<th class="${mClass(m)}">${m}</th>`).join('')+'</tr>'; for(const k of KPI_MASTER){khtml+=`<tr><td>${k.area}</td><td>${k.parameter}</td><td>${k.monthTarget}</td>`; for(const m of MONTHS){const r=ksaved[`${m}_${safeId(k.area+'_'+k.parameter)}`]||{}; const txt=[r.actual??'', r.judgt??'', r.trend??''].filter(x=>x!==''&&x!==undefined).join(' '); khtml+=`<td${tdClass(m)}>${txt}<br><small>${r.remarks??''}</small></td>`;} khtml+='</tr>';} kpiTable.innerHTML=khtml;
let ahtml='<tr><th>Section</th><th>Parameter</th><th>Dept / Division</th>'+MONTHS.map(m=>`<th class="${mClass(m)}">${m}</th>`).join('')+'</tr>'; let lastSec=''; for(const p of ABS_PARAMS){ if(p.section!==lastSec){ ahtml+=`<tr class="section-title"><td colspan="${MONTHS.length+3}">${p.section}</td></tr>`; lastSec=p.section; } for(const d of DEPTS){ ahtml+=`<tr><td>${p.section}</td><td>${p.param}</td><td>${d}</td>`; for(const m of MONTHS){const r=asaved[`${m}_${d}`]||{}; ahtml+=`<td${tdClass(m)}>${fmt(r[p.key])}</td>`;} ahtml+='</tr>'; } const label=p.calc==='avg'?'Division Avg':p.calc==='sum'?'Division Total':'Division Combined'; ahtml+=`<tr class="division-row"><td>${p.section}</td><td>${p.param}</td><td>${label}</td>`; for(const m of MONTHS){ahtml+=`<td${tdClass(m)}>${calcDivision(asaved,m,p)}</td>`;} ahtml+='</tr>'; } absTable.innerHTML=ahtml; setStatus('12 month dashboard with division Abs & OT average/total loaded.','ok'); }catch(e){setStatus('Dashboard load error: '+e.message,'bad'); console.error(e)} }
document.getElementById('refreshBtn').onclick=load; document.getElementById('excelBtn').onclick=()=>tableToExcel(`PE_3F_Division_Avg_12Month_Dashboard.xls`,`PE-3F Division Avg 12 Month Dashboard`,`<h3>KPI 12 Months</h3>${kpiTable.outerHTML}<h3>Abs & OT Division Avg / Total</h3>${absTable.outerHTML}`); document.getElementById('pptBtn').onclick=()=>tableToPpt(`PE_3F_Division_Avg_12Month_Dashboard.ppt`,`PE-3F Division Avg 12 Month Dashboard`,`<h3>KPI 12 Months</h3>${kpiTable.outerHTML}<h3>Abs & OT Division Avg / Total</h3>${absTable.outerHTML}`); setTimeout(load,500);
