import { firebaseConfig } from './firebase-config.js';
import { KPI_MASTER } from './kpi-master.js';
import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js';
import { getFirestore, doc, setDoc, getDoc, collection, getDocs, serverTimestamp, query, where } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';
const app = initializeApp(firebaseConfig); const db = getFirestore(app); const msg=document.getElementById('msg');
const DEVICE_USER = localStorage.getItem('kpi_device_user') || ('User-' + Math.random().toString(36).slice(2,7)); localStorage.setItem('kpi_device_user', DEVICE_USER);

const table=document.getElementById('kpiEntryTable'); const monthSelect=document.getElementById('monthSelect');
function safeId(s){return s.replace(/[^a-zA-Z0-9]/g,'_')}
function render(){table.innerHTML=`<tr><th>Area</th><th>Parameter / Requirement</th><th>102Ki Target</th><th>Month Target</th><th>Freq</th><th>${monthSelect.value} Actual</th><th>Judgt</th><th>Trend</th><th>Remarks</th></tr>`+KPI_MASTER.map(k=>{let id=safeId(k.area+'_'+k.parameter);return `<tr data-id="${id}" data-area="${k.area}" data-parameter="${k.parameter}"><td class='area'>${k.area}</td><td class='param'>${k.parameter}</td><td>${k.target102}</td><td>${k.monthTarget}</td><td>${k.freq}</td><td><input class='actual' type='number' step='any'></td><td><select class='judgt'><option>○</option><option>■</option><option>▲</option><option>◎</option><option>□</option></select></td><td><select class='trend'><option>→</option><option>↗</option><option>↘</option></select></td><td><input class='remarks'></td></tr>`}).join('')}
async function loadMonth(){try{render(); const m=monthSelect.value; msg.textContent='Loading...'; for(const tr of table.querySelectorAll('tr[data-id]')){const s=await getDoc(doc(db,'kpis',`${m}_${tr.dataset.id}`)); if(s.exists()){let d=s.data(); tr.querySelector('.actual').value=d.actual??''; tr.querySelector('.judgt').value=d.judgt??'○'; tr.querySelector('.trend').value=d.trend??'→'; tr.querySelector('.remarks').value=d.remarks??'';}} msg.textContent='Loaded.'}catch(e){msg.textContent='Load error: '+e.message; console.error(e)}}
async function saveAll(){try{const m=monthSelect.value; let c=0; msg.textContent='Saving...'; for(const tr of table.querySelectorAll('tr[data-id]')){await setDoc(doc(db,'kpis',`${m}_${tr.dataset.id}`),{month:m,area:tr.dataset.area,parameter:tr.dataset.parameter,actual:tr.querySelector('.actual').value===''?'':Number(tr.querySelector('.actual').value),judgt:tr.querySelector('.judgt').value,trend:tr.querySelector('.trend').value,remarks:tr.querySelector('.remarks').value,updatedBy:DEVICE_USER,updatedAt:serverTimestamp()},{merge:true}); c++;} msg.textContent=`Saved ${c} rows successfully.`}catch(e){msg.textContent='Save error: '+e.message; console.error(e)}}
monthSelect.addEventListener('change',loadMonth); document.getElementById('loadMonthBtn').addEventListener('click',loadMonth); document.getElementById('saveAllBtn').addEventListener('click',saveAll); render(); setTimeout(loadMonth,500);
